### ISSUE TITLE
输入指令没反应

### ISSUE THREAD

**Issue by CberYellowstone** [CAIMEOX/FastBuilder#4]
只能用get指令,其它的都没反应
在多个平台测试过(网易电脑be,网易手机be,官方手机be,win10be)
系统centos7,nodejs最新版,运行无报错,就是除了get或者getpos同类的指令没反应
不知道是什么原因,应该不是版本不兼容,换了3、4个版本号的游戏客户端了

**Comment by LNSSPsd** [comment]
When you're executing a FastBuilder command,the default block that FastBuilder will use to build the structure is `air`,so you should pass a `block (-b)` argument to build a visible structure.
Here's a example of building a round that made of iron blocks:
`round -r 6 -b iron_block`

**Comment by CberYellowstone** [comment]
>

> When you're executing a FastBuilder command,the default block that FastBuilder will use to build the structure is `air`,so you should pass a `block (-b)` argument to build a visible structure.
> Here's a example of building a round that made of iron blocks:
> `round -r 6 -b iron_block`

thanks,I'll try it later
