### ISSUE TITLE
Error: Cannot find module 'meowslib'

### ISSUE THREAD

**Issue by McPluss** [CAIMEOX/FastBuilder#5]
Require stack:
- E:\[NodeJS]\FastBuilder-master\Main.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:855:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1033:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (E:\[NodeJS]\FastBuilder-master\Main.js:1:15)
[90m    at Module._compile (internal/modules/cjs/loader.js:1144:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:993:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:892:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'E:\\[NodeJS]\\FastBuilder-master\\Main.js'[39m ]
}

**Comment by horsegame** [comment]
或许需要先安装必要的组件。（虽然作者没说，百度没找到meowslib是个啥东西，甚至没人会点进作者GitHub主页发现还有一个运行库之类的东西[https://github.com/CAIMEOX/libwebsocket](url)，但必应能让你发现惊喜。）You may install required components first.
在安装Node.js的时候一并安装npm package manager。如果没有修改安装选项的话会默认安装。Just install npm package manager. Normally it will be installed with Node.js.  
然后在命令提示符或者PowerShell中运行下面两条命令：Then run the following commands in cmd or PowerShell: 
```
npm install meowslib
npm install uuid
```
此时运行node Main.js，FastBuilder应该就能正常启动了。Now you can run FastBuilder properly by running node Main.js.

**Comment by horsegame** [comment]
@CAIMEOX 或许作者应该提醒一下安装那两个模块？我刚开始也是这个报错，也没找到怎么解决，后面如上文所讲是必应上有幸找到相关信息才得以运行成功。
